# Generated by Django 5.1.15 on 2026-05-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Business Owner'), ('finance', 'Finance Admin'), ('sales', 'Sales Admin'), ('inventory', 'Inventory Admin')], default='customer', max_length=20),
        ),
    ]
