# Generated by Django 5.1.15 on 2026-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(choices=[('online', 'Online shop only'), ('physical', 'Physical store')], default='online', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business settings',
                'verbose_name_plural': 'business settings',
            },
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='map_embed_url',
        ),
        migrations.AddField(
            model_name='branch',
            name='google_maps_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
