# Generated by Django 5.1.15 on 2026-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_email_alter_branch_google_maps_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/cards/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'home feature card',
                'verbose_name_plural': 'home feature cards',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
