# Generated by Django 5.1.15 on 2026-05-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homefeaturecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMediaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='This Is OREL', max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='home/media/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='home/media/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='home/media/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='home/media/')),
                ('video', models.FileField(blank=True, null=True, upload_to='home/media/videos/')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='home/media/posters/')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'home media section',
                'verbose_name_plural': 'home media section',
            },
        ),
    ]
